version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: secretstransfer.containerfile
    mem_limit: 512M
    restart: "always"
    ports:
      - "443:8443"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - internal
      - external

  redis:
    build:
      context: .
      dockerfile: redis.containerfile
    image: "redis:latest"
    mem_limit: 512M
    restart: "always"
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge